### ISSUE TITLE
Not working in iOS 10 :(

### ISSUE THREAD

**Issue by eriksonpk** [binarydev/ios-home-vs-lock-button#1]

**Comment by binarydev** [comment]
It is working in iOS 10 on a physical device, but not in the simulator as of iOS 10 beta 2. Haven't checked it since beta 2 though to see if the simulator has been fixed to accurately trigger the expected events once again.

**Comment by ainurb** [comment]
Hi, @binarydev 
First of all, thank you so much for your code, this is what I was searching for, and it works surprisingly perfect even 3 years later. 
But is it possible to make it work on swift?

**Comment by ImEric** [comment]
Hi, @ainurb 
I tried to port @binarydev 's amazing solution to support swift 3, you can check it out at the following link: [swift-home-button-vs-lock-button](https://github.com/ImEric/swift-home-vs-lock-button)
Please let me if it solves your problem:)

**Comment by ainurb** [comment]
Hi, @ImEric 
It works perfectly and it did solve my problem:) Before your code, I was forced to make bridging from objective-c to make this work, but your solution is much better and robust! Thank you!
